server {
  listen 8090;
  server_name _;
  client_max_body_size 64k;
  proxy_buffering off;
  location / {
    proxy_pass http://setup:8090;
    proxy_set_header Host 127.0.0.1;
    proxy_set_header X-Forwarded-For "";
    proxy_set_header X-Forwarded-Proto http;
  }
}
