export type PromptDefinition = {
  id: string;
  relativePath: string;
  title: string;
  group: string;
  active: boolean;
  timing: string;
  condition: string;
  purpose: string;
  usedBy: string;
  requiredVariables: string[];
};

export const PROMPT_CATALOG: readonly PromptDefinition[] = [
  {
    id: "director-system",
    relativePath: "director/system.md",
    title: "감독 기본 역할",
    group: "감독",
    active: true,
    timing: "프롬프트 로드 후 장면 구성 단계",
    condition: "Live 모드의 모든 작업에서 Codex 장면 기획 요청에 포함",
    purpose: "대본 순서 보존, 장면별 핵심 아이디어, 출력 형식 등 전체 기획 원칙을 지정합니다.",
    usedBy: "Codex 장면 기획",
    requiredVariables: [],
  },
  {
    id: "director-analyze-script",
    relativePath: "director/analyze-script.md",
    title: "대본 분석",
    group: "감독",
    active: false,
    timing: "장면 구성 단계에서 감독 기본 역할 다음",
    condition: "Live 모드의 모든 작업에서 사용자 대본을 삽입해 사용",
    purpose: "대본의 핵심 주제, 분위기와 시각적 연속성을 분석하도록 지시합니다.",
    usedBy: "Codex 장면 기획",
    requiredVariables: ["{{SCENARIO}}"],
  },
  {
    id: "storyboard-system",
    relativePath: "storyboard/system.md",
    title: "스토리보드 기본 규칙",
    group: "스토리보드",
    active: false,
    timing: "장면 구성 단계에서 대본 분석 다음",
    condition: "Live 모드의 모든 작업에서 장면 분할 규칙으로 사용",
    purpose: "실측 음성 길이, 자막 분리, 장면 간 연속성 등 슬라이드 구성 원칙을 지정합니다.",
    usedBy: "Codex 장면 기획",
    requiredVariables: [],
  },
  {
    id: "storyboard-split-scenes",
    relativePath: "storyboard/split-scenes.md",
    title: "장면 분할",
    group: "스토리보드",
    active: false,
    timing: "장면 구성 단계에서 실제 장면 JSON을 만들 때",
    condition: "Live 모드의 모든 작업에서 사용자 대본을 삽입해 사용",
    purpose: "내레이션, 화면 요약, 이미지 프롬프트와 연속된 장면 ID를 생성하도록 지시합니다.",
    usedBy: "Codex 장면 기획",
    requiredVariables: ["{{SCENARIO}}"],
  },
  {
    id: "continuity-select-assets",
    relativePath: "continuity/select-assets.md",
    title: "연속성 에셋 선정",
    group: "연속성",
    active: true,
    timing: "장면 구성과 동일한 Codex 요청 안에서 장면 분할 다음",
    condition: "Live 모드에서 보수적으로 반복 개체 후보를 선정하며 0개를 허용",
    purpose: "정체성 불일치가 서사를 손상하는 개체만 기준 에셋 후보로 선정합니다.",
    usedBy: "Codex 장면·연속성 통합 기획",
    requiredVariables: [],
  },
  {
    id: "continuity-assign-scene-references",
    relativePath: "continuity/assign-scene-references.md",
    title: "장면별 연속성 참조 할당",
    group: "연속성",
    active: true,
    timing: "장면 구성과 동일한 Codex 요청에서 에셋 선정 직후",
    condition: "선정된 에셋이 있는 장면과 없는 장면 모두에 적용",
    purpose: "실제 등장과 이미지 생성 참조를 분리하고 장면당 참조를 0~8개로 제한합니다.",
    usedBy: "Codex 장면·연속성 통합 기획",
    requiredVariables: [],
  },
  {
    id: "continuity-build-canonical-asset",
    relativePath: "continuity/build-canonical-asset.md",
    title: "연속성 기준 이미지 생성",
    group: "연속성",
    active: true,
    timing: "선정된 연속성 에셋의 기준 이미지 태스크 생성 시",
    condition: "continuity_assets가 비어 있지 않을 때 에셋당 정확히 한 번",
    purpose: "카테고리별 대표 구도와 불변 특성으로 기준 이미지 한 장을 생성합니다.",
    usedBy: "이미지 태스크 브로커",
    requiredVariables: ["{{CANONICAL_IDENTITY}}", "{{MUST_REMAIN_CONSISTENT}}", "{{ALLOWED_VARIATIONS}}", "{{ANCHOR_PROMPT}}", "{{STYLE_GUIDE}}"],
  },
  {
    id: "continuity-disabled",
    relativePath: "continuity/disabled.md",
    title: "연속성 OFF 지시",
    group: "연속성",
    active: true,
    timing: "장면 구성 시 연속성 유지가 OFF인 작업",
    condition: "사용자가 이미지 연속성 유지를 끈 경우에만 Codex 요청에 포함",
    purpose: "연속성 분석·에셋·참조를 생략하고 Style Bible만 유지합니다.",
    usedBy: "Codex 장면 기획",
    requiredVariables: [],
  },
  {
    id: "image-system",
    relativePath: "image/system.md",
    title: "이미지 생성 기본 규칙",
    group: "이미지",
    active: true,
    timing: "장면 구성 단계와 각 장면의 이미지 생성·편집 직전",
    condition: "Live 모드에서 기획 요청 및 모든 GPT Image 2 요청에 사용",
    purpose: "16:9 구도, 자막 안전영역, 글자·로고 금지와 영상 전체의 시각적 일관성을 지정합니다.",
    usedBy: "Codex 장면 기획 + GPT Image 2",
    requiredVariables: [],
  },
  {
    id: "image-build-prompt",
    relativePath: "image/build-image-prompt.md",
    title: "장면 이미지 프롬프트 작성",
    group: "이미지",
    active: true,
    timing: "장면 구성 단계에서 각 장면의 image_prompt를 만들 때",
    condition: "Live 모드의 모든 작업에서 장면 정보를 이미지 지시문으로 변환",
    purpose: "내레이션과 화면 요약을 실제 이미지 한 장으로 표현할 구체적인 프롬프트 작성법을 지정합니다.",
    usedBy: "Codex 장면 기획",
    requiredVariables: ["{{SCENE_JSON}}"],
  },
  {
    id: "image-reference-contract",
    relativePath: "image/reference-contract.md",
    title: "복수 이미지 참조 계약",
    group: "이미지",
    active: true,
    timing: "참조 에셋이 있는 장면 이미지 요청 직전",
    condition: "reference_asset_ids가 하나 이상인 장면",
    purpose: "참조 순서와 보존·허용 변화·비복사 규칙을 공급자 프롬프트에 매핑합니다.",
    usedBy: "이미지 태스크 브로커",
    requiredVariables: ["{{REFERENCE_MAP}}"],
  },
  {
    id: "image-generate-scene",
    relativePath: "image/generate-scene.md",
    title: "구조화 장면 이미지 생성",
    group: "이미지",
    active: true,
    timing: "각 장면 이미지 태스크의 합성 프롬프트 작성 시",
    condition: "모든 장면 이미지 생성",
    purpose: "구조화된 장면·연속성 결과와 Style Bible을 추가 LLM 호출 없이 합성합니다.",
    usedBy: "이미지 태스크 브로커",
    requiredVariables: ["{{SCENE_JSON}}", "{{REFERENCE_CONTRACT}}", "{{STYLE_GUIDE}}"],
  },
  {
    id: "image-style-guide",
    relativePath: "image/style-guide.md",
    title: "공통 스타일 가이드",
    group: "이미지",
    active: true,
    timing: "장면 구성 및 결정론적 대체 장면 생성 시",
    condition: "Live 기획 요청에 포함되며, Mock 모드와 누락 장면의 대체 프롬프트에도 직접 사용",
    purpose: "색상, 조명, 질감, 깊이감과 자막 안전영역 등 영상 전체의 공통 미술 방향을 유지합니다.",
    usedBy: "Codex 장면 기획 + 결정론적 장면 보정",
    requiredVariables: [],
  },
  {
    id: "repair-revise-image",
    relativePath: "repair/revise-image-prompt.md",
    title: "이미지 실패 프롬프트 보정",
    group: "복구",
    active: false,
    timing: "현재는 작업 시작 시 로드하고 스냅샷만 저장",
    condition: "자동 이미지 재작성 루프가 아직 연결되지 않아 현재 런타임에서는 호출하지 않음",
    purpose: "향후 이미지 생성 오류를 반영해 기존 장면 프롬프트를 최소 수정하는 복구 지시문입니다.",
    usedBy: "예약됨 — 현재 런타임 미사용",
    requiredVariables: ["{{SCENE_JSON}}", "{{ERROR}}"],
  },
  ...[
    ["narrative-story-intent", "narrative/story-intent.md", "이야기 의도", "구조 분석", "장면 계획 호출", "모든 작업", "전체 이야기 목적과 source unit 입력을 정의", ["{{SOURCE_UNITS}}"]],
    ["narrative-sequences", "narrative/analyze-sequences.md", "Sequence 분석", "구조 분석", "장면 계획 호출", "모든 작업", "연속 source unit을 상위 서사 단위로 묶음", []],
    ["narrative-groups", "narrative/analyze-scene-groups.md", "Scene group 분석", "구조 분석", "장면 계획 호출", "모든 작업", "Sequence 안의 국소 목적 단위를 정의", []],
    ["narrative-scenes", "narrative/analyze-scenes.md", "Scene 분석", "구조 분석", "장면 계획 호출", "모든 작업", "원문을 고치지 않고 장면 역할과 시각 설계를 생성", []],
    ["keycut-select", "keycut/select-keycuts.md", "Keycut 선택", "키컷", "장면 계획 호출", "모든 작업", "Sequence마다 기존 scene 하나를 기준 키컷으로 선택", []],
    ["keycut-contract", "keycut/reference-contract.md", "Keycut 참조 계약", "키컷", "파생 이미지 생성", "Keycut이 아닌 장면", "실제 keycut 파일을 첫 참조로 사용하는 계승·비복사 규칙", []],
    ["style-common", "style/common.md", "Style Bible 공통", "스타일", "장면 계획과 이미지 생성", "모든 작업", "영상 하나에 고정되는 Style Bible 규칙", ["{{IMAGE_STYLE}}"]],
    ["style-editorial", "style/presets/editorial-illustration.md", "에디토리얼 일러스트", "스타일", "장면 계획", "해당 스타일 선택 시", "정교한 편집 일러스트 preset", []],
    ["style-cinematic", "style/presets/cinematic-realism.md", "영화적 사실주의", "스타일", "장면 계획", "해당 스타일 선택 시", "영화 스틸 같은 사실적 preset", []],
    ["style-graphic", "style/presets/graphic-explainer.md", "그래픽 설명", "스타일", "장면 계획", "해당 스타일 선택 시", "구조와 인과를 설명하는 그래픽 preset", []],
  ].map((entry) => {
    const [id, relativePath, title, group, timing, condition, purpose, requiredVariables] = entry as [string, string, string, string, string, string, string, string[]];
    return {
      id, relativePath, title, group, active: true, timing, condition, purpose,
      usedBy: relativePath.startsWith("keycut/reference") ? "이미지 태스크 브로커" : "Codex 구조 계획",
      requiredVariables,
    } satisfies PromptDefinition;
  }),
] as const;
